services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    # command: sh -c "pnpm install && pnpm dev --host"
    tty: true
    stdin_open: true
